@echo off
setlocal

set PYTHONHOME=
set PYTHONPATH=
set ROS_LOG_DIR=D:\SimWorld\logs\ros
set FASTDDS_BUILTIN_TRANSPORTS=UDPv4
set USE_OLLAMA=1
set OLLAMA_MODEL=gpt-oss:latest
set SIM_CHASER_OLLAMA_MODEL=gpt-oss:latest
set OLLAMA_API_URL=http://10.8.0.132:11434/api/generate
set OLLAMA_API_URLS=http://10.8.0.132:11434/api/generate
set SIM_CHASER_OLLAMA_API_URL=http://10.8.0.132:11434/api/generate
set OLLAMA_OPENAI_URL=http://10.8.0.132:11434/v1
set OLLAMA_TIMEOUT_SEC=20
set SIM_CHASER_OLLAMA_NUM_PREDICT=512
set SIM_LOS_ENABLED=1
set SIM_CHASER_FAKE_OCCLUSION_PROB=0
set SIM_TEAM_CONFIG_FILE=D:\SimWorld\scripts\DroneROS\team_match_config.cmd
if exist "%SIM_TEAM_CONFIG_FILE%" if /I not "%SIM_IGNORE_TEAM_CONFIG%"=="1" call "%SIM_TEAM_CONFIG_FILE%"
if "%SIMWORLD_DRONE_MIN_Z%"=="" set SIMWORLD_DRONE_MIN_Z=100
if "%SIMWORLD_DRONE_MAX_Z%"=="" set SIMWORLD_DRONE_MAX_Z=700
if "%SIM_TARGET_BOUND_X%"=="" set SIM_TARGET_BOUND_X=1350
if "%SIM_TARGET_BOUND_Y%"=="" set SIM_TARGET_BOUND_Y=1350
if "%SIM_ARENA_BOUNDARY_MARGIN_CM%"=="" set SIM_ARENA_BOUNDARY_MARGIN_CM=90
if "%SIM_CHASER_CRUISE_Z%"=="" set SIM_CHASER_CRUISE_Z=450
if "%SIM_CHASER_VERTICAL_SPEED%"=="" set SIM_CHASER_VERTICAL_SPEED=240
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if not "%SIM_BLUE_BASE_SPEED%"=="" set SIM_CHASER_SPEED=%SIM_BLUE_BASE_SPEED%
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if not "%SIM_BLUE_INTERCEPT_SPEED%"=="" set SIM_CHASER_INTERCEPT_SPEED=%SIM_BLUE_INTERCEPT_SPEED%
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if not "%SIM_BLUE_SEARCH_SPEED%"=="" set SIM_CHASER_SEARCH_SPEED=%SIM_BLUE_SEARCH_SPEED%
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_SPEED%"=="" set SIM_CHASER_SPEED=250
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_INTERCEPT_SPEED%"=="" set SIM_CHASER_INTERCEPT_SPEED=285
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_SEARCH_SPEED%"=="" set SIM_CHASER_SEARCH_SPEED=190
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_SPEED%"=="250" set SIM_CHASER_SPEED=275
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_INTERCEPT_SPEED%"=="285" set SIM_CHASER_INTERCEPT_SPEED=325
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_SEARCH_SPEED%"=="190" set SIM_CHASER_SEARCH_SPEED=225
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_PRESSURE_SPEED_SCALE%"=="" set SIM_CHASER_PRESSURE_SPEED_SCALE=0.72
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_REACTION_DELAY_SEC%"=="" set SIM_CHASER_REACTION_DELAY_SEC=0.40
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_AIM_NOISE_CM%"=="" set SIM_CHASER_AIM_NOISE_CM=75
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_MISTAKE_CHANCE%"=="" set SIM_CHASER_MISTAKE_CHANCE=0.06
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_PRESSURE_HOLD_CHANCE%"=="" set SIM_CHASER_PRESSURE_HOLD_CHANCE=0.10
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_HEAT_MAX%"=="" set SIM_CHASER_HEAT_MAX=150
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_OVERHEATED_SPEED_SCALE%"=="" set SIM_CHASER_OVERHEATED_SPEED_SCALE=0.82
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_FINISH_RANGE_CM%"=="" set SIM_CHASER_FINISH_RANGE_CM=220
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_FINISH_SPEED%"=="" set SIM_CHASER_FINISH_SPEED=220
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" if "%SIM_CHASER_FINISH_COMMIT_SEC%"=="" set SIM_CHASER_FINISH_COMMIT_SEC=0.6
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" set SIM_SKIP_BRAIN_SPEED_PROMPT=1
if "%SIM_CHASER_SPEED%"=="" set SIM_CHASER_SPEED=260
if "%SIM_CHASER_INTERCEPT_SPEED%"=="" set SIM_CHASER_INTERCEPT_SPEED=300
if "%SIM_CHASER_SEARCH_SPEED%"=="" set SIM_CHASER_SEARCH_SPEED=200
if "%SIM_CHASER_PRESSURE_SPEED_SCALE%"=="" set SIM_CHASER_PRESSURE_SPEED_SCALE=0.78
if "%SIM_CATCH_DISTANCE%"=="" set SIM_CATCH_DISTANCE=160
if "%SIM_CHASER_REACTION_DELAY_SEC%"=="" set SIM_CHASER_REACTION_DELAY_SEC=0.25
if "%SIM_CHASER_TURN_RATE_DEG%"=="" set SIM_CHASER_TURN_RATE_DEG=180
if "%SIM_CHASER_AIM_NOISE_CM%"=="" set SIM_CHASER_AIM_NOISE_CM=45
if "%SIM_CHASER_MISTAKE_CHANCE%"=="" set SIM_CHASER_MISTAKE_CHANCE=0.03
if "%SIM_CHASER_PRESSURE_HOLD_CHANCE%"=="" set SIM_CHASER_PRESSURE_HOLD_CHANCE=0.15
if "%SIM_CHASER_HEAT_MAX%"=="" set SIM_CHASER_HEAT_MAX=180
if "%SIM_CHASER_HEAT_COOL_PER_SEC%"=="" set SIM_CHASER_HEAT_COOL_PER_SEC=24
if "%SIM_CHASER_OVERHEATED_SPEED_SCALE%"=="" set SIM_CHASER_OVERHEATED_SPEED_SCALE=0.9
if "%SIM_SKIP_BRAIN_SPEED_PROMPT%"=="1" (
    echo [chaser] Using saved team speed config; skipping individual speed prompt.
    echo [chaser] Team mode uses DroneB as blue_1; support drones are handled by run_team_support.cmd.
) else (
    set SIM_SPEED_ENV_FILE=%TEMP%\simworld_chaser_speeds_%RANDOM%.cmd
    powershell -NoProfile -ExecutionPolicy Bypass -File D:\SimWorld\scripts\DroneROS\configure_brain_speeds.ps1 -DefaultDrone chaser -OutputCmd "%SIM_SPEED_ENV_FILE%"
    if exist "%SIM_SPEED_ENV_FILE%" call "%SIM_SPEED_ENV_FILE%"
    if exist "%SIM_SPEED_ENV_FILE%" del "%SIM_SPEED_ENV_FILE%"
)
set PATH=D:\pixi_ws\.pixi\envs\default;D:\pixi_ws\.pixi\envs\default\Library\bin;D:\pixi_ws\.pixi\envs\default\Scripts;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0

if not exist D:\SimWorld\logs\ros mkdir D:\SimWorld\logs\ros

call D:\pixi_ws\ros2-windows\local_setup.bat
call D:\SimWorld\ros2_ws\install\local_setup.bat
set PYTHONPATH=D:\SimWorld\ros2_ws\src\simworld_drone_ros;%PYTHONPATH%

echo [chaser] Ollama model: %OLLAMA_MODEL%
echo [chaser] Ollama API: %OLLAMA_API_URL%
echo [chaser] Altitude: range=%SIMWORLD_DRONE_MIN_Z%-%SIMWORLD_DRONE_MAX_Z% cruise=%SIM_CHASER_CRUISE_Z% vz=%SIM_CHASER_VERTICAL_SPEED%
echo [chaser] Arena bounds: x=%SIM_TARGET_BOUND_X% y=%SIM_TARGET_BOUND_Y% margin=%SIM_ARENA_BOUNDARY_MARGIN_CM%
echo [chaser] Speeds: base=%SIM_CHASER_SPEED% intercept=%SIM_CHASER_INTERCEPT_SPEED% search=%SIM_CHASER_SEARCH_SPEED% pressure_scale=%SIM_CHASER_PRESSURE_SPEED_SCALE%
echo [chaser] Catch distance: %SIM_CATCH_DISTANCE% cm
D:\pixi_ws\.pixi\envs\default\python.exe -m simworld_drone_ros.duel.chaser_brain
