@echo off
setlocal

call "%~dp0env.cmd"
if exist "%SIM_TEAM_CONFIG_FILE%" if /I not "%SIM_IGNORE_TEAM_CONFIG%"=="1" call "%SIM_TEAM_CONFIG_FILE%"

set "SIMWORLD_HOST=127.0.0.1"
if "%SIMWORLD_PORT%"=="" set "SIMWORLD_PORT=9000"
set "SIMWORLD_USE_EXISTING_DRONES=1"
set "SIMWORLD_DRONE_AUTO_SPAWN=0"
set "SIMWORLD_TEAM_AUTO_SPAWN=0"
if "%SIMWORLD_DRONE_A_NAME%"=="" set "SIMWORLD_DRONE_A_NAME=DroneA"
if "%SIMWORLD_DRONE_B_NAME%"=="" set "SIMWORLD_DRONE_B_NAME=DroneB"
if "%SIMWORLD_DRONE_ASSET%"=="" set "SIMWORLD_DRONE_ASSET=StaticMeshActor"
if "%SIMWORLD_DRONE_SWEEP%"=="" set "SIMWORLD_DRONE_SWEEP=1"
if "%SIMWORLD_DIRECT_ON_SWEEP_BLOCK%"=="" set "SIMWORLD_DIRECT_ON_SWEEP_BLOCK=0"
if "%SIM_TARGET_BOUND_X%"=="" set "SIM_TARGET_BOUND_X=1350"
if "%SIM_TARGET_BOUND_Y%"=="" set "SIM_TARGET_BOUND_Y=1350"
if "%SIM_ARENA_BOUNDARY_COLLISION_ENABLED%"=="" set "SIM_ARENA_BOUNDARY_COLLISION_ENABLED=1"
if "%SIM_ARENA_BOUNDARY_MARGIN_CM%"=="" set "SIM_ARENA_BOUNDARY_MARGIN_CM=90"
if "%SIMWORLD_DRONE_MIN_Z%"=="" set "SIMWORLD_DRONE_MIN_Z=100"
if "%SIMWORLD_DRONE_MAX_Z%"=="" set "SIMWORLD_DRONE_MAX_Z=700"
if "%SIM_CATCH_DISTANCE%"=="" set "SIM_CATCH_DISTANCE=160"
if "%SIM_TEAM_CATCH_MODE%"=="" set "SIM_TEAM_CATCH_MODE=primary"
if "%SIM_TEAM_ROUND_MODE%"=="" set "SIM_TEAM_ROUND_MODE=tag"
if "%SIM_INACTIVE_DRONE_PARK_ENABLED%"=="" set "SIM_INACTIVE_DRONE_PARK_ENABLED=1"
if "%SIM_INACTIVE_DRONE_PARK_X%"=="" set "SIM_INACTIVE_DRONE_PARK_X=2800"
if "%SIM_INACTIVE_DRONE_PARK_Y%"=="" set "SIM_INACTIVE_DRONE_PARK_Y=2800"
if "%SIM_INACTIVE_DRONE_PARK_Z%"=="" set "SIM_INACTIVE_DRONE_PARK_Z=150"

echo [bridge] SimWorld=%SIMWORLD_HOST%:%SIMWORLD_PORT%
echo [bridge] Existing actors: %SIMWORLD_DRONE_A_NAME%, %SIMWORLD_DRONE_B_NAME%
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" echo [bridge] Team config: red=%SIM_RED_TEAM_SIZE% blue=%SIM_BLUE_TEAM_SIZE%
echo [bridge] Arena: bounds=(%SIM_TARGET_BOUND_X%,%SIM_TARGET_BOUND_Y%) margin=%SIM_ARENA_BOUNDARY_MARGIN_CM%

"%PYTHON_EXE%" -u -m simworld_drone_ros.bridge.ue_bridge
