@echo off
setlocal

call "%~dp0env.cmd"

(
  echo set "SIM_TEAM_MATCH_CONFIGURED=1"
  echo set "SIM_RED_TEAM_SIZE=5"
  echo set "SIM_BLUE_TEAM_SIZE=5"
  echo set "SIM_TEAM_ROUND_MODE=red_elimination"
  echo set "SIM_TEAM_CATCH_MODE=any"
  echo set "SIM_TEAM_START_ACTIVE=1"
  echo set "SIM_TEAM_SUPPORT_AUTOSTART=1"
  echo set "SIM_TEAM_USE_OLLAMA=1"
  echo set "SIM_TEAM_CONTROL_PRIMARIES=1"
  echo set "SIM_TEAM_IGNORE_DUEL_PRIMARY_CMDS=1"
  echo set "SIM_TEAM_PRIMARY_ELIMINATION_RESETS=0"
  echo set "SIM_TEAM_ELIMINATION_GRACE_SEC=3"
  echo set "SIM_CATCH_DISTANCE=220"
  echo set "SIM_RED_CRUISE_SPEED=210"
  echo set "SIM_RED_EVADE_SPEED=260"
  echo set "SIM_RED_BURST_SPEED=300"
  echo set "SIM_BLUE_BASE_SPEED=365"
  echo set "SIM_BLUE_INTERCEPT_SPEED=525"
  echo set "SIM_BLUE_SEARCH_SPEED=365"
  echo set "SIM_BLUE_SUPPORT_SPEED_SCALE=1.0"
  echo set "SIM_BLUE_DIRECT_COMMIT_DISTANCE_CM=1200"
  echo set "SIM_BLUE_ENDGAME_COMMIT_DISTANCE_CM=1600"
  echo set "SIM_DRONE_COLLISION_RADIUS_CM=35"
  echo set "SIM_TEAM_MIN_SEPARATION_CM=260"
  echo set "SIMWORLD_PUSH_ROTATION=0"
) > "%SIM_TEAM_CONFIG_FILE%"

echo [team] Saved 5v5 config: %SIM_TEAM_CONFIG_FILE%
type "%SIM_TEAM_CONFIG_FILE%"
