@echo off
setlocal

call "%~dp0env.cmd"
if exist "%SIM_TEAM_CONFIG_FILE%" if /I not "%SIM_IGNORE_TEAM_CONFIG%"=="1" call "%SIM_TEAM_CONFIG_FILE%"

set "USE_OLLAMA=1"
if "%OLLAMA_MODEL%"=="" set "OLLAMA_MODEL=gpt-oss:latest"
if "%SIM_TARGET_OLLAMA_MODEL%"=="" set "SIM_TARGET_OLLAMA_MODEL=%OLLAMA_MODEL%"
if "%OLLAMA_API_URL%"=="" set "OLLAMA_API_URL=http://10.8.0.132:11434/api/generate"
if "%OLLAMA_API_URLS%"=="" set "OLLAMA_API_URLS=%OLLAMA_API_URL%"
if "%SIM_TARGET_OLLAMA_API_URL%"=="" set "SIM_TARGET_OLLAMA_API_URL=%OLLAMA_API_URL%"
if "%OLLAMA_OPENAI_URL%"=="" set "OLLAMA_OPENAI_URL=http://10.8.0.132:11434/v1"
if "%OLLAMA_TIMEOUT_SEC%"=="" set "OLLAMA_TIMEOUT_SEC=20"
if "%SIM_LOS_ENABLED%"=="" set "SIM_LOS_ENABLED=1"
if "%SIM_TEAM_MATCH_CONFIGURED%"=="1" set "SIM_SKIP_BRAIN_SPEED_PROMPT=1"

if "%SIM_TARGET_SPEED%"=="" set "SIM_TARGET_SPEED=220"
if "%SIM_TARGET_CRUISE_SPEED%"=="" set "SIM_TARGET_CRUISE_SPEED=%SIM_TARGET_SPEED%"
if "%SIM_TARGET_EVADE_SPEED%"=="" set /A SIM_TARGET_EVADE_SPEED=%SIM_TARGET_SPEED%+45
if "%SIM_TARGET_BURST_SPEED%"=="" set /A SIM_TARGET_BURST_SPEED=%SIM_TARGET_SPEED%+115
if "%SIMWORLD_DRONE_MIN_Z%"=="" set "SIMWORLD_DRONE_MIN_Z=100"
if "%SIMWORLD_DRONE_MAX_Z%"=="" set "SIMWORLD_DRONE_MAX_Z=700"
if "%SIM_TARGET_BOUND_X%"=="" set "SIM_TARGET_BOUND_X=1350"
if "%SIM_TARGET_BOUND_Y%"=="" set "SIM_TARGET_BOUND_Y=1350"
if "%SIM_ARENA_BOUNDARY_MARGIN_CM%"=="" set "SIM_ARENA_BOUNDARY_MARGIN_CM=90"
if "%SIM_TARGET_CRUISE_Z%"=="" set "SIM_TARGET_CRUISE_Z=450"
if "%SIM_TARGET_VERTICAL_SPEED%"=="" set "SIM_TARGET_VERTICAL_SPEED=150"

echo [target] Team red=%SIM_RED_TEAM_SIZE% blue=%SIM_BLUE_TEAM_SIZE%
echo [target] Speeds: cruise=%SIM_TARGET_CRUISE_SPEED% evade=%SIM_TARGET_EVADE_SPEED% burst=%SIM_TARGET_BURST_SPEED%

"%PYTHON_EXE%" -u -m simworld_drone_ros.duel.target_brain
